### ISSUE TITLE
"Edit this page on GitHub" links broken

### ISSUE THREAD

**Issue by amouat** [sigstore/sigstore-website#101]
At the bottom of website pages e.g. https://docs.sigstore.dev/cosign/usage/ there is an "Edit this page on GitHub" which currently 404s.

An example link is https://github.com/sigstore/sigstore-website/tree/docs/edit/docs/content/en/cosign/usage.md

I think this should be https://github.com/sigstore/sigstore-website/edit/docs/content/en/cosign/usage.md or similar.

**Comment by znewman01** [comment]
CC @dlorenc

**Comment by ltagliaferri** [comment]
Resolved with #193

**Comment by znewman01** [comment]
#193 reintroduces #81, the issue that #88 fixed: the GitHub icon in the right hand corner now links to https://github.com/sigstore/sigstore-website (the main branch, not the docs branch).

<img width="1031" alt="Screen Shot 2022-07-10 at 5 10 49 PM" src="https://user-images.githubusercontent.com/873857/178165720-2856d5c5-254e-4245-8f60-6e84c5f90c7d.png">

See my above comment for a solution that handles both (but is substantially more work). A much simpler thing to do would be to make a new `sigstore/docs` repo and migrate the `docs` branch there. There's already [some support](https://github.com/sigstore/sigstore-website/issues/81#issuecomment-970191807) for doing so.

**Comment by ltagliaferri** [comment]
Thanks, @znewman01 for surfacing this. My thought was that the GitHub logo going to the main branch is not ideal but less of a concern compared to the completely broken "edit this page" link (going to a 404), and I agree there should be a longer-term fix. Though I don't have data about the click-through rate for these which could potentially inform a better solution. 

Thank you for surfacing that previous conversation on repos — I also have been thinking that a separate`docs` repo will lower the barrier to entry for docs contributions. I will write some more details about that for feedback.
