### ISSUE TITLE
Add docs around support

### ISSUE THREAD

**Issue by priyawadhwa** [sigstore/sigstore-website#113]
For people who are running into issues with sigstore, it would be nice to have a doc on the website which goes over:
* How to contact project maintainers
* Where to ask questions
* Links to any docs that might help debug issues

**Comment by endorama** [comment]
I'd be happy to contribute to this, but I need some more information.

> How to contact project maintainers

Which is the preferred way for contacting project maintainers? 

> Where to ask questions

Is there consensus about this? For example using GitHub discussions vs issues

**Comment by priyawadhwa** [comment]
> Which is the preferred way for contacting project maintainers?

Slack would be the best way! We can point to the #general channel and tag CODEOWNERS of that specific repo.

> Where to ask questions

Either Slack or Github Issues would be good :)

**Comment by endorama** [comment]
I added a page in the documentation about it. @priyawadhwa do you think is enough or we want a page in the main website?

**Comment by puerco** [comment]
I think we can close this one as done: https://docs.sigstore.dev/support
Thanks @endorama !
/cc @priyawadhwa

**Comment by priyawadhwa** [comment]
Thanks @endorama ! :D
