### ISSUE TITLE
use RSS feed from sigstore blog to drive events on main page

### ISSUE THREAD

**Issue by bobcallaway** [sigstore/sigstore-website#114]
**Description**

The "News & Events" section of the site only shows content from last July... could this perhaps be generated off of the RSS feed from [blog.sigstore.dev](https://blog.sigstore.dev)?

**Comment by mdunbavan** [comment]
This is a really good idea @bobcallaway

**Comment by mdunbavan** [comment]
I think we can integrate the feed very easily using this:

https://content.nuxtjs.org/integrations/#nuxtjsfeed

**Comment by endorama** [comment]
I stumbled upon this issue and created a PR for it. @mdunbavan I tried looking at `nuxtjs/feed` module but it seems to solve the opposite use case (creating a RSS feed for a NuxtJS site).

Waiting on your review :)

**Comment by dlorenc** [comment]
I just manually added a few that weren't all from the blog here: https://github.com/sigstore/sigstore-website/pull/117
