### ISSUE TITLE
Organize Rekor documentation and fix redundancies

### ISSUE THREAD

**Issue by cburkhardt27** [sigstore/sigstore-website#116]
**Description**

The Rekor documentation is a bit disorganized. There are a lot of redundancies and broken links. For example,

The Rekor [Overview](https://docs.sigstore.dev/rekor/overview) page has local server installation instructions that are out of date and partially broken. 

There are separate instructions for installing the rekor-server on the [Server setup](https://docs.sigstore.dev/rekor/server-setup) page that work but need to be cleaned up (eg. add instructions for database installation, standardize formatting, and fix broken links). 

There is also an [Installation](https://docs.sigstore.dev/rekor/installation) page that has release page links and go install`instructions for the rekor-server and the rekor-cli, but nothing else. 

There is a [CLI](https://docs.sigstore.dev/rekor/CLI) page that includes build instructions for the rekor-cli and GPG sign/upload instructions that overlap with the purpose of the [Signing and Uploading Other Types](https://docs.sigstore.dev/rekor/sign-upload) page.

There are also two public instance pages: [Public instance](https://docs.sigstore.dev/rekor/public-instance) and [Auditing the Public Instance](https://docs.sigstore.dev/rekor/auditing-public-instance).

I think the information on all these pages should be reorganized to something like:

**Overview**: This page would only explain the general purpose of Rekor. The “Usage and Installation” subsection would link to the Installation page.

**Installation**: This page would contain all of the instructions for installing both rekor-cli and rekor server.
	**rekor-cli**:
           -release page
           -go install
           -git clone 
           **rekor-server**:
           -release page
           -go install
           -Manual setup
                      ----Database install
                      ----Trillian build and run
                      ----Local rekor server build and run

**CLI**: this page would outline using the CLI after installation. It defaults to using GPG for instructions but links to the Signing and Uploading Other Types page for other types (and the GPG instructions in the Signing and Uploading Other Types page would be removed).
-Signing
-Uploading
-Verifying
-Get Entry
-Log info
-Search

**Public Instance:** this page would combine the  Public Instance and Auditing Public Instance pages, since they’re both quite short and deal with the same topic.

If this update makes sense, I’m happy to do the reorganization/general clean-up to resolve the issue. I already have some notes about updating the local rekor-server install instructions, in particular.

**Comment by lukehinds** [comment]
sgtm @cburkhardt27 , I would go ahead and start working on this, they are all valid recommendations

**Comment by ltagliaferri** [comment]
Merged in #123
