### ISSUE TITLE
Docs: Cloud Provider Overview

### ISSUE THREAD

**Issue by dlorenc** [sigstore/sigstore-website#118]
We support some integrations with cloud providers, but they aren't really listed anywhere. Things like KMS, CA APIs, and keyless/oidc support bridge across individual tools (fulcio/cosign), so there's no great spot today.

Maybe we could use a "Sigstore on AWS", "Sigstore on GCP", "Sigstore on Azure" set of pages.

Build system integrations would be good too!

**Comment by dlorenc** [comment]
cc @ltagliaferri

**Comment by ltagliaferri** [comment]
I agree these pages would be great to have. I'll assign to myself and start scoping this (open to collaboration). Let me know any thoughts you have on timeline

**Comment by ltagliaferri** [comment]
Closing as ported to [sigstore/docs](https://github.com/sigstore/docs)
