### ISSUE TITLE
Sigstore.dev hamburger menu hidden on Pixel

### ISSUE THREAD

**Issue by kimsterv** [sigstore/sigstore-website#132]
A friend reported that the hamburger menu is "hidden" on a pixel and you have to scroll right to see it:
![image](https://user-images.githubusercontent.com/228135/157922819-64c6f312-ea14-44c5-9ef6-989ee1b49ddf.png)

**Comment by lukehinds** [comment]
Get an iPhone @kimsterv  !

Just kidding :) 

@mdunbavan I don't know much about vue mobile rendering, any tips for where to hunt.

**Comment by kimsterv** [comment]
lol. I have an iphone. Works great on iphone :)

**Comment by mdunbavan** [comment]
Hey @lukehinds @kimsterv I can patch a fix up next week for you :) it is a very simple css overflow fix on an element that is overlapping the bounding container.

**Comment by gtirloni** [comment]
Same issue on Samsung S21 Ultra with Chrome.

**Comment by remram44** [comment]
Found this because I'm browsing the GitHub after finding no information about anything on the website. If course I wouldn't have known to find links by **scrolling the page to the right**. This needs to be fixed ASAP.

**Comment by Neilblaze** [comment]
@kimsterv Can I take a shot if it's up for grabs? If yes, would you mind assigning me please? Thanks! :)

**Comment by remram44** [comment]
@Neilblaze no one has worked on it in the year it's been an open issue, so you don't have to worry about someone getting to it before you do.

**Comment by Neilblaze** [comment]
@remram44 😆 
Thanks for the followup. I'm on it! 😄

**Comment by kimsterv** [comment]
Thank you 🙏

**Comment by ltagliaferri** [comment]
@Neilblaze feel free to open a PR to fix this, thank you 😄
