### ISSUE TITLE
We should have a version selector

### ISSUE THREAD

**Issue by DennyHoang** [sigstore/sigstore-website#152]
**Description**

Currently, the docs shown on the sigstore.dev website are of the latest iteration of the docs only.
It would be nice and probably correct to have a version selector if users are using an older version.

**Comment by ltagliaferri** [comment]
Hi @DennyHoang — I am in the process of closing out issues to start to migrate the docs site to the new sigstore/docs repo. As this is a heavier lift compared to some of the other open issues, I ported it over to that repo so I can close it out here. Thank you for filing it, and I agree with you about versioning the docs. 

New issue: https://github.com/sigstore/docs/issues/2
