### ISSUE TITLE
wrong flag in Working with blobs

### ISSUE THREAD

**Issue by raulcabello** [sigstore/sigstore-website#163]
**Description**

There is an error in this part of the website https://docs.sigstore.dev/cosign/working_with_blobs#signing-blobs-as-files
`--cert` is not a valid flag for `cosign sign-blob`, `--output-certificate` should be used instead.

This:
```
This is output to stdout by default, but can be redirected to a file with the --cert flag.
```
should be like this:
```
This is output to stdout by default, but can be redirected to a file with the --output-certificate flag.
```

**Comment by ltagliaferri** [comment]
It looks like this has been addressed, not finding any `--cert` flag on this page now. Thanks for filing the issue! Closing this out.
