### ISSUE TITLE
Once helm chart for policy-controller gets renamed, update docs.

### ISSUE THREAD

**Issue by vaikas** [sigstore/sigstore-website#164]
**Description**

Once the (helm chart rename)[https://github.com/sigstore/helm-charts/issues/201] happens, we need to update a pointer to it here.
https://github.com/sigstore/sigstore-website/blob/docs/content/en/cosign/kubernetes.md

**Comment by ltagliaferri** [comment]
It looks like there have been updates to have the policy-controller section and that all the references to `cosigned` were removed. I could not pull them up in a search except for older blog posts: 
* [Spooky Updates for Sigstore!](https://blog.sigstore.dev/spooky-october-updates-for-sigstore-87a2b72172c1)
* [Don’t Panic: A Playbook for Handling Account Compromise with Sigstore](https://blog.sigstore.dev/dont-panic-a-playbook-for-handling-account-compromise-with-sigstore-ee299dca5144)
* [Verifying Container Image Signatures from an OCI Registry in Kubernetes](https://blog.sigstore.dev/verify-oci-container-image-signatures-in-kubernetes-33663a9ec7d8)

I'll close this out but let me know if there is something that still needs addressing.
