### ISSUE TITLE
"Signing Other Types" link in quick start gives a 404 error

### ISSUE THREAD

**Issue by pbrkr** [sigstore/sigstore-website#209]
Looking at https://docs.sigstore.dev/cosign/overview/#other-formats, the link "Signing Other Types" (https://docs.sigstore.dev/cosign/overview/other_types) results in a 404 error. Perhaps it should go to https://docs.sigstore.dev/cosign/other_types.

**Comment by ltagliaferri** [comment]
Thanks for reporting this! Also was informed of an issue about a link error on the policy-controller installation page so I'll address these both in a PR.
