### ISSUE TITLE
Broken internal links

### ISSUE THREAD

**Issue by lemeurherve** [sigstore/sigstore-website#221]
**Description**
On [the "Getting started" cosign page](https://docs.sigstore.dev/cosign/overview/#getting-started-quick-start) (and maybe other), all internal links are broken and return "Page not found", ex:

> ### Prerequisites
> You'll need to [install Cosign](https://docs.sigstore.dev/cosign/overview/installation) first, and you will need access to a container registry.

They should point to `https://docs.sigstore.dev/cosign/<some-page>` instead of `https://docs.sigstore.dev/cosign/overview/<some-page>` 

I've looked at https://github.com/sigstore/sigstore-website/blob/docs/content/en/cosign/overview.md but didn't see anything wrong, and when running the website locally the links are corrects: 

> `You'll need to [install Cosign](http://localhost:3000/cosign/installation) first, and you will need access to a container registry.`

Note: in both cases, the links have the same HTML content, ex: `<a href="installation">install Cosign</a>`

**Version**
N/A

**Comment by ericsmalling** [comment]
Probably same issue causing "intallation instructions" link on https://docs.sigstore.dev/policy-controller/overview/ to point to 
https://docs.sigstore.dev/policy-controller/overview/installation instread of the https://docs.sigstore.dev/policy-controller/installation
