### ISSUE TITLE
Add Slack to Footer

### ISSUE THREAD

**Issue by hrittikhere** [sigstore/sigstore-website#252]
**Description**
Slack is the easiest way for users, contributors and other participants to get going. The Link for Slack is not visible in the footer:

![image](https://user-images.githubusercontent.com/67012359/230720195-1ee37171-4a4f-4604-8643-846d93fb6438.png)

I think we should add that like other projects have done while maintaining the format: 
![image](https://user-images.githubusercontent.com/67012359/230720261-d08265de-4abf-4175-ad61-b00183020966.png)

Please let me know what you think about this :) I would love to work on this if this sounds like an appropriate change

**Comment by hrittikhere** [comment]
Just tried and tested and this should look like something below: 
![image](https://user-images.githubusercontent.com/67012359/230722184-39af3191-5ab0-4572-9d42-686c1be1e6af.png)

**Comment by Sukriti-sood** [comment]
Yes, it is the needed addition, as link to slack should be accessible easily.

**Comment by hrittikhere** [comment]
Sure, can you assign me?
