### ISSUE TITLE
Duplicate "What is the current status of the project"

### ISSUE THREAD

**Issue by imjasonh** [sigstore/sigstore-website#26]
From https://sigstore.dev/what_is_sigstore/ ([in this repo](https://github.com/sigstore/sigstore-website/blob/main/content/docs/what_is_sigstore.md)):

> ## What is the current status of the project
> We now have a fully functioning transparency log named 'rekor'. Rekor consists of a server and client tooling to make entries and query for inclusion. It has a customizable schema framework and pluggable PKI framework.
> 
> At present the WebPKI and client signing tooling is under prototype development and is not available for general use.

...and later, at the bottom of the page:

> ## What is the current status of the project
> As of time of writing [24/06/2021] we have a working transparency log (rekor), that is fully operation as a standalone service. Files are available to run this in GKE. Work is now underway to mature the WebPKI (fuclio) and develop client tools for various package managers and upstream communities

I don't know if the former supercedes the latter, or if they each provide complimentary information and should just be consolidated into one section. In either case, links to relevant work to learn more and find updates would also be useful.

**Comment by mdunbavan** [comment]
Closing this issue because those docs are going to be removed and we are using a separate repo for the docs content to be maintained.

**Comment by mdunbavan** [comment]
@imjasonh here is the repo for docs https://github.com/sigstore/sigstore.github.io
