### ISSUE TITLE
Incorrect architecture naming

### ISSUE THREAD

**Issue by lukehinds** [sigstore/sigstore-website#28]
It should be 'Fulcio Certificate Authority' , not Cosign Certificate Authority:

![image](https://user-images.githubusercontent.com/7058938/128765353-d177f78f-f844-4a34-b630-7927707c1b54.png)

**Comment by lukehinds** [comment]
Some others as well

Fulcio provides a certificate, not a signature. (well it does sign the CSR, but this make it sounds like it signs the artifact).

**Comment by lukehinds** [comment]
found another 

https://www.sigstore.dev/img/system_architecture_summary-01.svg

**Comment by mdunbavan** [comment]
Closing issue because svgs have now been updated
