### ISSUE TITLE
Line separator symbol is visible on home page text string

### ISSUE THREAD

**Issue by devmoran** [sigstore/sigstore-website#29]
- Noticed and logged by [@sorumuras](https://github.com/sormuras).

**Actual**
- "LSEP" (Line separator) symbol is visible on `root` at 'A new standard for signing, verifying  and protecting software'
- Chrome, Windows.

![image (3)](https://user-images.githubusercontent.com/4757853/128843532-6a5b9464-9b3c-4565-8173-da5d34982699.png)

**Expected**
- LSEP symbol as an invisible character / does not display LSEP

**Comment by sormuras** [comment]
Also/already visible here:

![image](https://user-images.githubusercontent.com/2319838/128844953-c025a91c-07b9-44da-9cdf-f1b8de79af96.png)

https://github.com/sigstore/sigstore-website/blob/b70d5f89214a32d4047a58675a7a53843aa1452a/content/home.md#L10
