### ISSUE TITLE
Outdated FAQ: "What's the current status?"

### ISSUE THREAD

**Issue by adrinjalali** [sigstore/sigstore-website#37]
This part of the FAQ seems outdated, it states:

> What's the current status?
> 
> We’re working hard to release v1.0 in July. At the time of writing, we have a working transparency log that’s fully operational as a standalone service, Rekor. It consists of a server and client tooling to make entries and query for inclusion. Files are available to run this in GKE. Work’s also underway to mature the WebPKI (Fulcio) and develop client tools for different package managers and upstream communities.

But version 1.0 is already released.

**Comment by lukehinds** [comment]
good catch, will get this updated.

**Comment by adrinjalali** [comment]
Kinda related, I'm not sure if this is up to date, it may be:

![beta](https://user-images.githubusercontent.com/1663864/129938448-f7fd4dc0-be48-4fef-a63c-134cb9cb723f.png)

**Comment by ltagliaferri** [comment]
In researching the edX course, I found that there are over 1,100 members (now there are over 1,200 on Slack), and over 2,800 commits. I am not sure about org updates, but I'm happy to [update with those figures](https://github.com/sigstore/sigstore-website/blob/2d84b2a7392efdda9d13e87fd6fef813eec0e05a/content/setup/info.json).

**Comment by dlorenc** [comment]
Sounds good to me!
