### ISSUE TITLE
Privacy Policy and Terms of Use Links Missing

### ISSUE THREAD

**Issue by ocdtrekkie** [sigstore/sigstore-website#66]
**Description**

The footer of the page refers to a bunch of legal terms, but none of them are available. Plain text cites the sentence fragment "Privacy Policy and Terms of Use." which contains no links. The terms appear to exist somewhere in this repo, but I cannot fathom how to reach them from the website.

Additionally, while "Forms on this site are protected by reCAPTCHA and the Google Privacy Policy and Terms of Service apply.", I would be on my own to locate Google's onerous terms myself if I wanted to know how they impacted me.

**Comment by lukehinds** [comment]
"Forms on this site are protected by reCAPTCHA and the Google Privacy Policy and Terms of Service apply." this looks like copy-pasta to me and I am happy to get it deleted.  I will look into the privacy policy.  Thanks for reporting.

**Comment by endorama** [comment]
I tried to add links for the privacy policy and the terms of use, but it seems those pages are not already available online.

**Comment by ocdtrekkie** [comment]
Glad to see this resolved!
