### ISSUE TITLE
Site still refers to August 2021 stable release

### ISSUE THREAD

**Issue by mlieberman85** [sigstore/sigstore-website#70]
https://github.com/sigstore/sigstore-website/blob/main/content/story/info.json

and

https://github.com/sigstore/sigstore-website/blob/main/components/textBanner.vue

both refer to Sigstore 1.0 release on August 2021 but other parts of the page still refer to Sigstore in beta. I know some stuff is 1.0 and a few things are almost 1.0 but might be worthwhile to clarify?

**Comment by endorama** [comment]
I looked at project releases today and the plan for sigstore GA is part of [this board](https://github.com/orgs/sigstore/projects/5/views/1).

Given that is still beta, I think it would make sense to change it to `stable release due soon` and link to the GA board (or a GA tracking issue). @lukehinds what do you think?

**Comment by k4leung4** [comment]
@priyawadhwa fyi

**Comment by priyawadhwa** [comment]
thanks @k4leung4 !
