### ISSUE TITLE
Where is the docs.sigstore.dev code?

### ISSUE THREAD

**Issue by philips** [sigstore/sigstore-website#81]
**Question**

What is the repo for docs.sigstore.dev? Can the github icon in the corner of docs.sigstore.dev please link to that repo? Or ideally the source file for each page? I want to fix a bug on the docs but can’t figure it out.

**Comment by philips** [comment]
For example the “link” that says “link” on this page: https://docs.sigstore.dev/fulcio/overview#usage-and-installation

**Comment by lukehinds** [comment]
Docs are in their own branch https://github.com/sigstore/sigstore-website/tree/docs

Its not an ideal set up tbh, I would prefer them in a seperate repo myself.

**Comment by philips** [comment]
@lukehinds Gah, well the README and the github icon on the docs.sigstore.dev website should link to the right branch at least.
