### ISSUE TITLE
document minimum viable Go code block to use cosign as a Go module from another project

### ISSUE THREAD

**Issue by developer-guy** [sigstore/sigstore-website#84]
**Description**

We all know to cosign is excellent. So IMHO, we should support documentation about how people who might want o use it in their tooling can use cosign as a Go module which can help us increase tooling around cosign. Again IMHO, we should provide two samples, one for how to use cosign with public/private key pairs, latter is Keyless mode.

cc: @dentrax @lukehinds @dlorenc @hectorj2f

**Comment by hectorj2f** [comment]
Generally it sounds good to me, I believe you mean to create some docs that explain how to inject these function calls into any main.go file, right ?

**Comment by developer-guy** [comment]
yes, exactly @hectorj2f. Think of it as an explanation of how people can use cosign as a Go module 🎁

**Comment by ltagliaferri** [comment]
Closing as ported to [sigstore/docs](https://github.com/sigstore/docs)
