### ISSUE TITLE
Add research / historical section to documentation

### ISSUE THREAD

**Issue by Foxboron** [sigstore/sigstore-website#93]
Using Transparency Logs to secure Supply Chains has a had several research papers and projects published since around 2016. It would probably be a good idea to document them for historical context?

[Software Distribution Transparency and Auditability](https://arxiv.org/abs/1711.07278)

[Contour: A Practical System for Binary Transparency](https://arxiv.org/abs/1712.08427)

[Reproducible Builds: Break a log, good things come in trees](https://bora.uib.no/bora-xmlui/handle/1956/20411)

I'm sure @SantiagoTorres also has some more suggestions :)

I'm sure a section like this would be useful in the future when there are research being done utilizing sigstore

**Comment by SantiagoTorres** [comment]
I actually was collecting a list of papers for some interested people  in slack! :+1:

**Comment by dlorenc** [comment]
Yeah this would be great!

**Comment by ltagliaferri** [comment]
I made a first pass on this in #201 but I was not able to find this list of papers in Slack you mentioned @SantiagoTorres — I think it's because we can no longer search into the Slack past
